name: Test ddr_plugin
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      #with:
      #  node-version: 'latest'

    - name: Install Mockoon
      run: npm install -g @mockoon/cli

    - name: List files
      run: ls -l
    
    - name: Start Mockoon server
      run: mockoon-cli start --data ./mockoon.json
      
    - name: Install ArgoCD CLI
      id: install_argocd
      shell: bash
      run: |
          curl -X 'POST' 'http://localhost:3000/api/login' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"password": "PASSWORD", "username": "alexandre-roy"}'
