name: Test ddr_plugin
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Mockoon
      run: npm install -g @mockoon/cli

    - name: Start Mockoon server
      run: mockoon-cli start -d ./path/to/your/mockoon/files
