name: Test ddr_plugin
on: [push]

env:
  # Plugin name/directory where the code for the plugin is stored 
  PLUGIN_NAME: pub_ddr_processing
  # python notation to test running inside plugin
  #  TESTS_RUN_FUNCTION: test.test_suite.test_package
  # Docker settings
  DOCKER_IMAGE: qgis/qgis

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        docker_tags: [latest]
        # docker_tags: [release-3_26, latest]
        # docker_tags: [release-3_16, release-3_18, latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2

    - name: Install Mockoon
      run: npm install -g @mockoon/cli

    - name: List files
      run: ls -l
    
    - name: Start Mockoon server
      run: mockoon-cli start --data ./pub_ddr_processing/mockoon.json
      
    - name: Install ArgoCD CLI and test Mockoon server
      id: install_argocd
      shell: bash
      run: |
          curl -X 'POST' 'http://localhost:3000/api/login' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"password": "PASSWORD", "username": "alexandre-roy"}'
          
          
    - name: Docker pull and create qgis-testing-environment
      run: |
        docker pull "$DOCKER_IMAGE":${{ matrix.docker_tags }}
        docker run -d --name qgis-testing-environment -v "$GITHUB_WORKSPACE":/tests_directory -e DISPLAY=:99 "$DOCKER_IMAGE":${{ matrix.docker_tags }}
        
    - name: Docker set up QGIS
      run: |
        
        # Install and start Mockoon
        docker exec qgis-testing-environment sh -c "npm install -g @mockoon/cli"
        docker exec qgis-testing-environment sh -c "mockoon-cli start --data /tests_directory/pub_ddr_processing/mockoon.json"
        
        docker exec qgis-testing-environment sh -c "apt install libxcb-cursor0"
        docker exec qgis-testing-environment sh -c "export XDG_RUNTIME_DIR=/tests_directory"
        docker exec qgis-testing-environment sh -c "export RUNLEVEL=3"

        docker exec qgis-testing-environment sh -c "cd tests_directory/pub_ddr_processing"
        
        set +e
        docker exec qgis-testing-environment sh -c "qgis_process run /tests_directory/pub_ddr_processing/patch_mockoon_user.py"
        echo "exitcode=$?" >> $GITHUB_OUTPUT
        
        # docker exec qgis-testing-environment sh -c "qgis_setup.sh $PLUGIN_NAME"


        docker exec qgis-testing-environment sh -c "rm -f /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"
        docker exec qgis-testing-environment sh -c "ln -s /tests_directory /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"
        docker exec qgis-testing-environment sh -c "ls -l /root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/$PLUGIN_NAME"

        docker exec qgis-testing-environment sh -c "qgis_process run pub_ddr_processing:login --distance_units=meters --area_units=m2 --ellipsoid=EPSG:7019 --AUTHENTICATION=p3m9sdd --ENVIRONMENT=Test"
        #docker exec qgis-testing-environment sh -c "qgis_process run pub_ddr_processing:publish --distance_units=meters --area_units=m2 --ellipsoid=EPSG:7030 --QGIS_FILE_EN='test5_en.qgs' --QGIS_FILE_FR='dummy\test5_fr.qgs' --DEPARTMENT=nrcan --METADATA_UUID=5c8559e4-ee59-47cc-8572-637c40f9aebb --EMAIL='foo.bar@nrcan-rncan.gc.ca' --DOWNLOAD_INFO_ID=DDR_DOWNLOAD1 --QGS_SERVER_ID=DDR_QGS_Internal --KEEP_FILES=No"


        

